package org.hska.vislab.eshop.model.db;

// Generated 02.06.2006 12:13:10 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */

public class Account implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 4271237415955388734L;

	private String email;

	private String street;

	private String city;

	private String zipcode;

	private String country;

	private boolean administrator;

	private String password;

	private String firstname;

	private String lastname;

	private Set<Order> orders = new HashSet<Order>();

	// Constructors

	/** default constructor */
	public Account() {
	}

	/** minimal constructor */
	public Account(String email, boolean administrator, String password,
			String firstname, String lastname) {
		this.email = email;
		this.administrator = administrator;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
	}

	/** full constructor */
	public Account(String email, String street, String city, String zipcode,
			String country, boolean administrator, String password,
			String firstname, String lastname, Set<Order> orders) {
		this.email = email;
		this.street = street;
		this.city = city;
		this.zipcode = zipcode;
		this.country = country;
		this.administrator = administrator;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.orders = orders;
	}

	// Property accessors

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public boolean isAdministrator() {
		return this.administrator;
	}

	public void setAdministrator(boolean administrator) {
		this.administrator = administrator;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
