package org.hska.vislab.eshop.model.db;

// Generated 02.06.2006 12:13:10 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.HashSet;
import java.util.Set;

/**
 * Commoditygroup generated by hbm2java
 */

public class Commoditygroup implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 9066994889273869404L;

	private Integer id;

	private Commoditygroup commoditygroup;

	private String name;

	private String description;

	private Set<Commoditygroup> commoditygroups = new HashSet<Commoditygroup>();

	private Set<Item> items = new HashSet<Item>();

	// Constructors

	/** default constructor */
	public Commoditygroup() {
	}

	/** minimal constructor */
	public Commoditygroup(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	/** full constructor */
	public Commoditygroup(Integer id, Commoditygroup commoditygroup,
			String name, String description,
			Set<Commoditygroup> commoditygroups, Set<Item> items) {
		this.id = id;
		this.commoditygroup = commoditygroup;
		this.name = name;
		this.description = description;
		this.commoditygroups = commoditygroups;
		this.items = items;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Commoditygroup getCommoditygroup() {
		return this.commoditygroup;
	}

	public void setCommoditygroup(Commoditygroup commoditygroup) {
		this.commoditygroup = commoditygroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Commoditygroup> getCommoditygroups() {
		return this.commoditygroups;
	}

	public void setCommoditygroups(Set<Commoditygroup> commoditygroups) {
		this.commoditygroups = commoditygroups;
	}

	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
