package org.hska.vislab.eshop.model.db;

// Generated 02.06.2006 12:13:10 by Hibernate Tools 3.1.0 beta1JBIDERC2

/**
 * Item generated by hbm2java
 */

public class Item implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = -3853676558419053694L;

	private Integer id;

	private Commoditygroup commoditygroup;

	private String name;

	private Integer currentAmount;

	private Integer criticalAmount;

	private String description;

	private float price;
	
	private String imgurl;

	// Constructors

	/** default constructor */
	public Item() {
	}

	/** minimal constructor */
	public Item(Integer id, Commoditygroup commoditygroup, String name,
			Integer currentAmount, Integer criticalAmount, float price) {
		this.id = id;
		this.commoditygroup = commoditygroup;
		this.name = name;
		this.currentAmount = currentAmount;
		this.criticalAmount = criticalAmount;
		this.price = price;
	}

	/** full constructor */
	public Item(Integer id, Commoditygroup commoditygroup, String name,
			Integer currentAmount, Integer criticalAmount, String description,
			float price) {
		this.id = id;
		this.commoditygroup = commoditygroup;
		this.name = name;
		this.currentAmount = currentAmount;
		this.criticalAmount = criticalAmount;
		this.description = description;
		this.price = price;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Commoditygroup getCommoditygroup() {
		return this.commoditygroup;
	}

	public void setCommoditygroup(Commoditygroup commoditygroup) {
		this.commoditygroup = commoditygroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getCurrentAmount() {
		return this.currentAmount;
	}

	public void setCurrentAmount(Integer currentAmount) {
		this.currentAmount = currentAmount;
	}

	public Integer getCriticalAmount() {
		return this.criticalAmount;
	}

	public void setCriticalAmount(Integer criticalAmount) {
		this.criticalAmount = criticalAmount;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getImgurl() {
		return imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

}
