package org.hska.vislab.eshop.model.db;

// Generated 02.06.2006 12:13:10 by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;

/**
 * Order generated by hbm2java
 */

public class Order implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = -1465232902038411167L;

	private Integer odernumber;

	private Account account;

	private boolean delivered;

	private float total;

	private Date date;

	// Constructors

	/** default constructor */
	public Order() {
	}

	/** minimal constructor */
	public Order(Integer odernumber, Account account, boolean delivered) {
		this.odernumber = odernumber;
		this.account = account;
		this.delivered = delivered;
	}

	/** full constructor */
	public Order(Integer odernumber, Account account, boolean delivered,
			float total, Date date) {
		this.odernumber = odernumber;
		this.account = account;
		this.delivered = delivered;
		this.total = total;
		this.date = date;
	}

	// Property accessors

	public Integer getOdernumber() {
		return this.odernumber;
	}

	public void setOdernumber(Integer odernumber) {
		this.odernumber = odernumber;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public boolean isDelivered() {
		return this.delivered;
	}

	public void setDelivered(boolean delivered) {
		this.delivered = delivered;
	}

	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
